[ai]
required = true

[auth]
enabled = true
providers = ["email"]

[[secret]]
name = "WHATSAPP_GRAPH_URL"
expose = true

[[secret]]
name = "WHATSAPP_ACCESS_TOKEN"
expose = true

[[secret]]
name = "WHATSAPP_PHONE_NUMBER_ID"
expose = true

[[secret]]
name = "WHATSAPP_VERIFY_TOKEN"
expose = true

[[secret]]
name = "GROQ_API_KEY"
expose = true

[[secret]]
name = "MSG91_AUTH_KEY"
expose = true
[[secret]]
name = "LITELLM_URL"
expose = true

[[secret]]
name = "LITELLM_API_KEY"
expose = true

[[secret]]
name = "LITELLM_MODEL"
expose = true