-- CareFlow workflow/event trail for real-world hospital handoffs.
ALTER TABLE care_encounters ADD COLUMN IF NOT EXISTS current_stage text NOT NULL DEFAULT 'registered';
ALTER TABLE care_encounters ADD COLUMN IF NOT EXISTS priority text NOT NULL DEFAULT 'normal';

CREATE TABLE IF NOT EXISTS workflow_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hospital_id bigint NOT NULL REFERENCES hospitals(id) ON DELETE CASCADE,
  patient_id bigint NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  encounter_id bigint NULL REFERENCES care_encounters(id) ON DELETE SET NULL,
  event_type text NOT NULL,
  stage text NULL,
  actor_user_id text NULL,
  actor_staff_id bigint NULL REFERENCES staff_profiles(id) ON DELETE SET NULL,
  entity_type text NULL,
  entity_id text NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_workflow_events_patient
  ON workflow_events(hospital_id,patient_id,created_at DESC);

CREATE INDEX IF NOT EXISTS idx_workflow_events_encounter
  ON workflow_events(hospital_id,encounter_id,created_at DESC);

CREATE INDEX IF NOT EXISTS idx_workflow_events_stage
  ON workflow_events(hospital_id,stage,created_at DESC);