-- Operational handoffs missing from the core clinical record.
ALTER TABLE lab_orders ADD COLUMN IF NOT EXISTS sample_collected_at timestamp;
ALTER TABLE lab_orders ADD COLUMN IF NOT EXISTS processing_started_at timestamp;
ALTER TABLE lab_orders ADD COLUMN IF NOT EXISTS verified_at timestamp;
ALTER TABLE lab_orders ADD COLUMN IF NOT EXISTS verified_by text;
ALTER TABLE lab_orders ADD COLUMN IF NOT EXISTS doctor_notified_at timestamp;

CREATE TABLE IF NOT EXISTS pharmacy_dispenses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hospital_id bigint NOT NULL REFERENCES hospitals(id) ON DELETE CASCADE,
  patient_id bigint NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  medication_id bigint NULL REFERENCES medications(id) ON DELETE SET NULL,
  encounter_id bigint NULL REFERENCES care_encounters(id) ON DELETE SET NULL,
  quantity numeric NOT NULL DEFAULT 1,
  dispensed_by text,
  status text NOT NULL DEFAULT 'dispensed',
  notes text,
  dispensed_at timestamp NOT NULL DEFAULT now(),
  created_at timestamp NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_pharmacy_dispenses_patient ON pharmacy_dispenses(hospital_id,patient_id,dispensed_at DESC);

CREATE TABLE IF NOT EXISTS ops_tasks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hospital_id bigint NOT NULL REFERENCES hospitals(id) ON DELETE CASCADE,
  patient_id bigint NULL REFERENCES patients(id) ON DELETE SET NULL,
  encounter_id bigint NULL REFERENCES care_encounters(id) ON DELETE SET NULL,
  title text NOT NULL,
  description text,
  department text,
  assigned_staff_id bigint NULL REFERENCES staff_profiles(id) ON DELETE SET NULL,
  priority text NOT NULL DEFAULT 'normal',
  status text NOT NULL DEFAULT 'open',
  due_at timestamp,
  created_by text,
  completed_at timestamp,
  completed_by text,
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_ops_tasks_open ON ops_tasks(hospital_id,status,priority,due_at);
CREATE INDEX IF NOT EXISTS idx_ops_tasks_patient ON ops_tasks(hospital_id,patient_id,created_at DESC);