CREATE TABLE IF NOT EXISTS insurance_claims (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hospital_id bigint NOT NULL REFERENCES hospitals(id) ON DELETE CASCADE,
  patient_id bigint NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  admission_id bigint NULL REFERENCES admissions(id) ON DELETE SET NULL,
  payer_name text NOT NULL,
  policy_number text,
  claim_number text,
  status text NOT NULL DEFAULT 'pending',
  claimed_amount numeric NOT NULL DEFAULT 0,
  approved_amount numeric NOT NULL DEFAULT 0,
  notes text,
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_insurance_claims_patient ON insurance_claims(hospital_id,patient_id,created_at DESC);

CREATE TABLE IF NOT EXISTS discharge_checklists (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hospital_id bigint NOT NULL REFERENCES hospitals(id) ON DELETE CASCADE,
  admission_id bigint NOT NULL UNIQUE REFERENCES admissions(id) ON DELETE CASCADE,
  clinical_clearance boolean NOT NULL DEFAULT false,
  reports_ready boolean NOT NULL DEFAULT false,
  medication_reconciled boolean NOT NULL DEFAULT false,
  billing_cleared boolean NOT NULL DEFAULT false,
  insurance_status text NOT NULL DEFAULT 'not_applicable',
  payment_status text NOT NULL DEFAULT 'pending',
  discharge_medicines text,
  summary text,
  cleared_by text,
  cleared_at timestamp,
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);