CREATE TABLE IF NOT EXISTS patient_sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hospital_id bigint NOT NULL REFERENCES hospitals(id) ON DELETE CASCADE,
  patient_id bigint NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  token_hash text NOT NULL UNIQUE,
  expires_at timestamp without time zone NOT NULL,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  last_seen_at timestamp without time zone NOT NULL DEFAULT now()
)