import { browser } from "hatchable";
import { db } from "../lib/db.js";
import { requirePermission } from "../lib/authz.js";
export const access="user";
export const methods=["GET"];
export default async function(req,res){
 const ctx=await requirePermission(req,res,"action.clinical.view"); if(!ctx)return;
 const pid=Number(req.query?.patient_id||0); if(!pid)return res.status(400).json({error:"Patient id is required"});
 const p=await db.query("SELECT p.*,h.name AS hospital_name,h.phone AS hospital_phone,h.address AS hospital_address FROM patients p JOIN hospitals h ON h.id=p.hospital_id WHERE p.id=$1 AND p.hospital_id=$2 LIMIT 1",[pid,ctx.hospitalId]);
 if(!p.rows[0])return res.status(404).json({error:"Patient not found"}); const a=p.rows[0];
 const m=await db.query("SELECT m.*,d.name AS doctor_name FROM medications m LEFT JOIN doctors d ON d.id=m.doctor_id WHERE m.patient_id=$1 AND m.hospital_id=$2 ORDER BY m.prescribed_at DESC LIMIT 20",[pid,a.hospital_id]);
 const v=await db.query("SELECT clinical_notes,started_at FROM doctor_visits WHERE patient_id=$1 AND hospital_id=$2 ORDER BY started_at DESC LIMIT 1",[pid,a.hospital_id]);
 const html='<!doctype html><html><body style="font-family:Arial,sans-serif;padding:32px;color:#17202a"><h1 style="margin:0;color:#0f766e">'+String(a.hospital_name||'CareFlow Clinic')+'</h1><div>'+String(a.hospital_address||'')+' · '+String(a.hospital_phone||'')+'</div><hr><h2>Prescription</h2><div><strong>'+String(a.name)+'</strong> · '+String(a.uhid||'')+' · '+String(a.phone||'')+'</div><div style="margin-top:10px">Date: '+new Date().toLocaleDateString('en-IN')+'</div><table style="width:100%;border-collapse:collapse;margin-top:24px"><tr><th style="text-align:left;border-bottom:1px solid #ddd;padding:8px">Medicine</th><th style="padding:8px">Dose</th><th style="padding:8px">Frequency</th><th style="padding:8px">Duration</th><th style="text-align:left;padding:8px">Instructions</th></tr>'+m.rows.map(x=>'<tr><td style="border-bottom:1px solid #eee;padding:8px">'+String(x.medicine_name)+'</td><td style="padding:8px">'+String(x.dose||'')+'</td><td style="padding:8px">'+String(x.frequency||'')+'</td><td style="padding:8px">'+String(x.duration||'')+'</td><td style="padding:8px">'+String(x.instructions||'')+'</td></tr>').join('')+'</table>'+(v.rows[0]?'<h3>Clinical note</h3><p>'+String(v.rows[0].clinical_notes||'')+'</p>':'')+'<p style="margin-top:40px;font-size:12px;color:#667085">Generated by CareFlow. Prescription decisions remain with the treating clinician.</p></body></html>';
 const pdf=await browser.pdf("data:text/html,"+encodeURIComponent(html));res.setHeader("Content-Type","application/pdf");res.setHeader("Content-Disposition",'inline; filename="careflow-prescription.pdf"');return res.send(Buffer.from(pdf));
}